name: no_more_background
description: "Stop Android™ apps running in the background"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.6.1+206010

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  dynamic_color: ^1.8.1
  dynamic_yaru: ^0.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.4
  jni: ^1.0.0
  logging: ^1.3.0
  material_symbols_icons: ^4.2892.0
  mutex: ^3.1.0
  package_info_plus: ^9.0.0
  platform_linux: ^0.1.2+1
  shizuku_api: ^1.2.2
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  stow_codecs: ^1.4.0
  stow_plain: ^0.6.0
  super_context_menu: ^0.9.1
  url_launcher: ^6.3.2
  yaru: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  golden_screenshot: ^11.0.1
  junitify: ^0.1.2
  jnigen: ^0.16.0
  intl: ^0.20.2
  yaml: ^3.1.3
  sealed_languages: ^3.1.0
  path: ^1.9.1

flutter:
  uses-material-design: true

  assets:
    - LICENSE.md
    - assets/cocomaterial/
    - assets/icon/icon.png
    - assets/icon/LICENSE
    - submodules/lawnicons/app/assets/appfilter.xml
    - submodules/lawnicons/LICENSE

    - path: assets/Delta-Icons-License.txt
      platforms: [windows, linux, macos]
    - path: submodules/Delta-Icons/app/src/main/assets/appfilter.xml
      platforms: [windows, linux, macos]
    - path: submodules/Delta-Icons/app/src/main/res/drawable-nodpi/
      platforms: [windows, linux, macos]
    - path: submodules/lineage_wiki/licenses/LICENSE
      platforms: [windows, linux, macos]
    - path: submodules/lineage_wiki/images/devices/small/
      platforms: [windows, linux, macos]

# ./scripts/generate_icons.sh
flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: true
  adaptive_icon_background: "assets/icon/icon_android_bg.png"
  adaptive_icon_foreground: "assets/icon/icon_android_fg.png"
  adaptive_icon_monochrome: "assets/icon/icon_android_mono.png"

  windows:
    generate: true
    icon_size: 256
