// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `androidx.core.util.Pair`
extension type Pair<$F extends jni$_.JObject?, $S extends jni$_.JObject?>._(
  jni$_.JObject _$this
) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'androidx/core/util/Pair');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Pair> type = $Pair$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/Object;Ljava/lang/Object;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(F object, S object1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory Pair($F? object, $S? object1) {
    final _$$classRef = _class.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<Pair<$F, $S>>();
  }

  static final _id_create = _class.staticMethodId(
    r'create',
    r'(Ljava/lang/Object;Ljava/lang/Object;)Landroidx/core/util/Pair;',
  );

  static final _create =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public androidx.core.util.Pair<A, B> create(A object, B object1)`
  /// The returned object must be released after use, by calling the [release] method.
  static Pair<$A?, $B?>? create<
    $A extends jni$_.JObject?,
    $B extends jni$_.JObject?
  >($A? object, $B? object1) {
    final _$$classRef = _class.reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    final _$object1 = object1?.reference ?? jni$_.jNullReference;
    return _create(
      _$$classRef.pointer,
      _id_create.pointer,
      _$object.pointer,
      _$object1.pointer,
    ).object<Pair<$A?, $B?>?>();
  }
}

extension Pair$$Methods<$F extends jni$_.JObject?, $S extends jni$_.JObject?>
    on Pair<$F, $S> {
  static final _id_first = Pair._class.instanceFieldId(
    r'first',
    r'Ljava/lang/Object;',
  );

  /// from: `public final F first`
  /// The returned object must be released after use, by calling the [release] method.
  $F? get first => _id_first.getNullable(this, jni$_.JObject.type) as $F?;

  static final _id_second = Pair._class.instanceFieldId(
    r'second',
    r'Ljava/lang/Object;',
  );

  /// from: `public final S second`
  /// The returned object must be released after use, by calling the [release] method.
  $S? get second => _id_second.getNullable(this, jni$_.JObject.type) as $S?;

  static final _id_equals = Pair._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public boolean equals(java.lang.Object object)`
  core$_.bool equals(jni$_.JObject? object) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_hashCode$1 = Pair._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int hashCode()`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_toString$1 = Pair._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? toString$1() {
    final _$$selfRef = reference;
    return _toString$1(
      _$$selfRef.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString?>();
  }
}

final class $Pair$Type$ extends jni$_.JType<Pair> {
  @jni$_.internal
  const $Pair$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroidx/core/util/Pair;';
}

/// from: `com.adilhanney.no_more_background.RootShellUtil`
extension type RootShellUtil._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/adilhanney/no_more_background/RootShellUtil',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<RootShellUtil> type = $RootShellUtil$Type$();
  static final _id_get$isRooted = _class.staticMethodId(r'isRooted', r'()Z');

  static final _get$isRooted =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public boolean isRooted()`
  static core$_.bool get isRooted {
    final _$$classRef = _class.reference;
    return _get$isRooted(_$$classRef.pointer, _id_get$isRooted.pointer).boolean;
  }

  static final _id_run = _class.staticMethodId(
    r'run',
    r'(Ljava/lang/String;)Landroidx/core/util/Pair;',
  );

  static final _run =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public androidx.core.util.Pair<java.lang.Integer, java.lang.String> run(java.lang.String command)`
  /// The returned object must be released after use, by calling the [release] method.
  static Pair<jni$_.JInteger?, jni$_.JString?> run(jni$_.JString command) {
    final _$$classRef = _class.reference;
    final _$command = command.reference;
    return _run(
      _$$classRef.pointer,
      _id_run.pointer,
      _$command.pointer,
    ).object<Pair<jni$_.JInteger?, jni$_.JString?>>();
  }
}

final class $RootShellUtil$Type$ extends jni$_.JType<RootShellUtil> {
  @jni$_.internal
  const $RootShellUtil$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/adilhanney/no_more_background/RootShellUtil;';
}
