#!/usr/bin/env dart
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:collection/collection.dart';
import 'package:intl/intl.dart';

late final String newVersionName;
late final int newVersionCode;
const String editor = 'zed';

const dummyChangelog = 'Release_notes_will_be_added_here';

Future<void> main(List<String> args) async {
  if (args.length != 2) {
    throw ArgumentError('Usage: ./scripts/apply_version.dart 1.2.3 102030');
  }
  newVersionName = args[0];
  newVersionCode = int.parse(args[1]);
  await updateAllFiles();
}

Future<void> updateAllFiles() async {
  // update pubspec
  await File('pubspec.yaml').replace({
    // e.g. version: 5.5.0+5050
    RegExp(r'version: .+'): 'version: $newVersionName+$newVersionCode',
  });

  // create metadata changelog
  final changelogFile = File('metadata/en-US/changelogs/$newVersionCode.txt');
  if (changelogFile.existsSync()) {
    print('Changelog file already exists');
  } else {
    print('Creating a blank changelog file');
    await changelogFile.writeAsString('• $dummyChangelog\n');
  }

  // update flatpak changelog
  final metainfoFile = File(
    'flatpak/com.adilhanney.no_more_background.metainfo.xml',
  );
  final metainfoLines = metainfoFile.readAsLinesSync();
  final originalMetainfoLines = metainfoLines.toList();
  if (metainfoFile.contains(newVersionName)) {
    print('<release> tag already exists in flatpak file');
  } else {
    print('Adding a new <release> tag to flatpak file');
    final date = DateFormat('yyyy-MM-dd').format(DateTime.now().toUtc());
    final releaseTag =
        '''
        <release version="$newVersionName" date="$date">
            <description>
                <ul>
                    <li>$dummyChangelog</li>
                </ul>
            </description>
        </release>''';
    final index =
        metainfoLines.indexWhere((line) => line.endsWith('<releases>')) + 1;
    metainfoLines.insert(index, releaseTag);
  }
  _generateMetainfoDescription(metainfoLines);
  _generateMetainfoScreenshots(metainfoLines);
  if (!listEquals(metainfoLines, originalMetainfoLines)) {
    if (metainfoLines.last.isNotEmpty) metainfoLines.add('');
    await metainfoFile.writeAsString(metainfoLines.join('\n'));
  }

  print('');
  print('Make sure to update the changelog files:');
  print('  - ${changelogFile.path}');
  print('  - ${metainfoFile.path}');
  print('And then run:');
  print('  - ./scripts/translate_changelogs.dart');

  // open changelog files in editor
  await Process.run(editor, [changelogFile.path], runInShell: true);
  await Process.run(editor, [metainfoFile.path], runInShell: true);
}

void _generateMetainfoDescription(List<String> metainfoLines) {
  var start =
      metainfoLines.indexWhere((line) => line.endsWith('<description>')) + 1;
  final end = metainfoLines.indexWhere(
    (line) => line.endsWith('</description>'),
  );
  assert(start > 0 && end > 0, '<description/> tag not found');

  metainfoLines.removeRange(start, end); // remove old changelog entries
  metainfoLines.insert(
    start++,
    '        <!--\n'
    '        DO NOT EDIT.\n'
    '        Any modifications will be overwritten.\n'
    '        This <description/> tag is generated by apply_version.dart from `metadata/*/full_description.txt`.\n'
    '        -->',
  );

  final localesWithFullDescription = Directory('metadata')
      .listSync()
      .whereType<Directory>()
      .where((dir) => !dir.path.endsWith('en-US'))
      .where(
        (dir) => dir.listSync().any(
          (file) => file.path.endsWith('/full_description.txt'),
        ),
      )
      .map((dir) => dir.path.split('/').last)
      .sorted();
  for (final localeCode in [null, ...localesWithFullDescription]) {
    final txtFile = File(
      'metadata/${localeCode ?? 'en-US'}/full_description.txt',
    );
    final paragraphs = txtFile.readAsStringSync().split(RegExp(r'\n{2,}'));
    final openTag = localeCode == null ? '<p>' : '<p xml:lang="$localeCode">';
    for (final paragraph in paragraphs) {
      if (paragraph.isEmpty) continue;
      metainfoLines.insert(start++, ' ' * 8 + openTag);
      metainfoLines.insert(start++, ' ' * 12 + paragraph);
      metainfoLines.insert(start++, ' ' * 8 + '</p>');
    }
    metainfoLines.insert(start++, '');
  }
}

void _generateMetainfoScreenshots(List<String> metainfoLines) {
  const catalogue = [
    (name: '2_apps', caption: 'Manage which apps can run in the background'),
    (name: '1_connect', caption: 'Connect your Android™ device via adb'),
    (name: '3_system_apps', caption: 'Also manage system apps if needed'),
  ];
  final localesWithScreenshots = Directory('metadata')
      .listSync()
      .where((dir) => !dir.path.endsWith('en-US'))
      .where(
        (dir) => File(
          '${dir.path}/images/flathubScreenshots/2_apps.png',
        ).existsSync(),
      )
      .map((dir) => dir.path.split('/').last)
      .sorted();

  var start =
      metainfoLines.indexWhere((line) => line.endsWith('<screenshots>')) + 1;
  final end = metainfoLines.indexWhere(
    (line) => line.endsWith('</screenshots>'),
  );
  assert(start > 0 && end > 0, '<screenshots/> tag not found');

  metainfoLines.removeRange(start, end); // remove old changelog entries
  metainfoLines.insert(
    start++,
    '        <!--\n'
    '        DO NOT EDIT.\n'
    '        Any modifications will be overwritten.\n'
    '        This <screenshots/> tag is generated by apply_version.dart.\n'
    '        -->',
  );

  for (final (:name, :caption) in catalogue) {
    final openTag = name == '2_apps'
        ? '<screenshot type="default">'
        : '<screenshot>';
    const indent = '        ';
    metainfoLines.insert(start++, indent + openTag);
    metainfoLines.insert(start++, '$indent    <caption>$caption</caption>');
    metainfoLines.insert(
      start++,
      '$indent    <image>https://raw.githubusercontent.com/adil192/no_more_background/refs/tags/v$newVersionName/metadata/en-US/images/flathubScreenshots/$name.png</image>',
    );
    for (final locale in localesWithScreenshots) {
      metainfoLines.insert(
        start++,
        '$indent    <image xml:lang="$locale">https://raw.githubusercontent.com/adil192/no_more_background/refs/tags/v$newVersionName/metadata/$locale/images/flathubScreenshots/$name.png</image>',
      );
    }
    metainfoLines.insert(start++, '$indent</screenshot>');
  }
}

extension on File {
  bool contains(Pattern pattern) {
    final content = readAsStringSync();
    return content.contains(pattern);
  }

  Future<void> replace(Map<RegExp, String> replacements) async {
    var matches = 0;
    final lines = await readAsLines();
    for (var i = 0; i < lines.length; i++) {
      for (final pattern in replacements.keys) {
        if (pattern.hasMatch(lines[i])) {
          matches++;
          lines[i] = lines[i].replaceFirst(pattern, replacements[pattern]!);
        }
      }
    }
    if (lines.last.isNotEmpty) lines.add('');
    await writeAsString(lines.join('\n'));

    if (matches >= replacements.length) {
      print('Updated $path with all $matches replacements');
    } else {
      print(
        'Updated $path with $matches out of ${replacements.length} '
        'replacements (${replacements.length - matches} missed)',
      );
    }
  }
}

bool listEquals<T>(List<T> list, List<T> other) {
  if (list.length != other.length) return false;
  for (var i = 0; i < list.length; i++) {
    if (list[i] != other[i]) return false;
  }
  return true;
}
